#!/bin/bash

res=$(dialyzer --plt_info)
part1=${res:1:3}
part2=${res:0:3}
if [ $part1 == "dia" ]
then
	dialyzer --build_plt --apps erts kernel stdlib mnesia
else
	if [ $part2 == "The" ]
	then
		exit 0
	else
		echo "$part"
		echo "dialyzer needs to be installed"
		exit 1
	fi
fi